version: '3.9'

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@fastapi_db:5432/postgres
    depends_on:
      - fastapi_db

  fastapi_db:
    image: postgres:16.1
    ports:
      - "5433:5432" # Porta 5433 no host, 5432 no container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
